import {
    Activity,
    AlarmClock,
    Apple,
    Ban,
    BedDouble,
    Bike,
    BookOpen,
    Brain,
    Briefcase,
    Brush,
    CalendarCheck2,
    CannabisOff,
    CigaretteOff,
    ChefHat,
    CircleStop,
    Clock3,
    Coffee,
    Droplets,
    Dumbbell,
    Flame,
    Flower2,
    Footprints,
    GlassWater,
    GraduationCap,
    HandHeart,
    Heart,
    House,
    Languages,
    Laptop,
    Leaf,
    ListChecks,
    LucideIcon,
    Medal,
    Moon,
    Music,
    NotebookPen,
    PenLine,
    Pill,
    Plane,
    Phone,
    Smile,
    Sparkles,
    Target,
    Timer,
    Sunrise,
    Utensils,
    Wallet,
    WineOff
} from "./icons";

export type HabitIconOption = {
    key: string;
    labelKey: string;
    icon: LucideIcon;
};

export const HABIT_ICON_OPTIONS: HabitIconOption[] = [
    { key: "sparkles", labelKey: "settings.habitIconSparkles", icon: Sparkles },
    { key: "activity", labelKey: "settings.habitIconActivity", icon: Activity },
    { key: "alarmClock", labelKey: "settings.habitIconAlarmClock", icon: AlarmClock },
    { key: "bedDouble", labelKey: "settings.habitIconBedDouble", icon: BedDouble },
    { key: "ban", labelKey: "settings.habitIconBan", icon: Ban },
    { key: "bike", labelKey: "settings.habitIconBike", icon: Bike },
    { key: "brush", labelKey: "settings.habitIconBrush", icon: Brush },
    { key: "calendarCheck", labelKey: "settings.habitIconCalendarCheck", icon: CalendarCheck2 },
    { key: "cannabisOff", labelKey: "settings.habitIconCannabisOff", icon: CannabisOff },
    { key: "cigaretteOff", labelKey: "settings.habitIconCigaretteOff", icon: CigaretteOff },
    { key: "chefHat", labelKey: "settings.habitIconChefHat", icon: ChefHat },
    { key: "circleStop", labelKey: "settings.habitIconCircleStop", icon: CircleStop },
    { key: "clock3", labelKey: "settings.habitIconClock3", icon: Clock3 },
    { key: "coffee", labelKey: "settings.habitIconCoffee", icon: Coffee },
    { key: "droplets", labelKey: "settings.habitIconDroplets", icon: Droplets },
    { key: "dumbbell", labelKey: "settings.habitIconDumbbell", icon: Dumbbell },
    { key: "flame", labelKey: "settings.habitIconFlame", icon: Flame },
    { key: "flower2", labelKey: "settings.habitIconFlower2", icon: Flower2 },
    { key: "footprints", labelKey: "settings.habitIconFootprints", icon: Footprints },
    { key: "glassWater", labelKey: "settings.habitIconGlassWater", icon: GlassWater },
    { key: "graduationCap", labelKey: "settings.habitIconGraduationCap", icon: GraduationCap },
    { key: "handHeart", labelKey: "settings.habitIconHandHeart", icon: HandHeart },
    { key: "brain", labelKey: "settings.habitIconBrain", icon: Brain },
    { key: "book", labelKey: "settings.habitIconBook", icon: BookOpen },
    { key: "briefcase", labelKey: "settings.habitIconBriefcase", icon: Briefcase },
    { key: "heart", labelKey: "settings.habitIconHeart", icon: Heart },
    { key: "house", labelKey: "settings.habitIconHouse", icon: House },
    { key: "languages", labelKey: "settings.habitIconLanguages", icon: Languages },
    { key: "laptop", labelKey: "settings.habitIconLaptop", icon: Laptop },
    { key: "leaf", labelKey: "settings.habitIconLeaf", icon: Leaf },
    { key: "listChecks", labelKey: "settings.habitIconListChecks", icon: ListChecks },
    { key: "medal", labelKey: "settings.habitIconMedal", icon: Medal },
    { key: "sunrise", labelKey: "settings.habitIconSunrise", icon: Sunrise },
    { key: "moon", labelKey: "settings.habitIconMoon", icon: Moon },
    { key: "music", labelKey: "settings.habitIconMusic", icon: Music },
    { key: "notebookPen", labelKey: "settings.habitIconNotebookPen", icon: NotebookPen },
    { key: "penLine", labelKey: "settings.habitIconPenLine", icon: PenLine },
    { key: "apple", labelKey: "settings.habitIconApple", icon: Apple },
    { key: "pill", labelKey: "settings.habitIconPill", icon: Pill },
    { key: "plane", labelKey: "settings.habitIconPlane", icon: Plane },
    { key: "utensils", labelKey: "settings.habitIconUtensils", icon: Utensils },
    { key: "phone", labelKey: "settings.habitIconPhone", icon: Phone },
    { key: "smile", labelKey: "settings.habitIconSmile", icon: Smile },
    { key: "target", labelKey: "settings.habitIconTarget", icon: Target },
    { key: "timer", labelKey: "settings.habitIconTimer", icon: Timer },
    { key: "wallet", labelKey: "settings.habitIconWallet", icon: Wallet },
    { key: "wineOff", labelKey: "settings.habitIconWineOff", icon: WineOff }
];

const LEGACY_EMOJI_TO_ICON_KEY: Record<string, string> = {
    "🌟": "sparkles",
    "✨": "sparkles",
    "🏃": "activity",
    "🏃‍♂️": "activity",
    "🏃‍♀️": "activity",
    "⏰": "alarmClock",
    "🛏️": "bedDouble",
    "🛌": "bedDouble",
    "🚫": "ban",
    "⛔": "ban",
    "🚴": "bike",
    "🚴‍♂️": "bike",
    "🚴‍♀️": "bike",
    "🎨": "brush",
    "🗓️": "calendarCheck",
    "📅": "calendarCheck",
    "🍃": "cannabisOff",
    "🌿🚫": "cannabisOff",
    "🚭": "cigaretteOff",
    "👨‍🍳": "chefHat",
    "👩‍🍳": "chefHat",
    "🍳": "chefHat",
    "🛑": "circleStop",
    "🕒": "clock3",
    "☕": "coffee",
    "💧": "droplets",
    "🚰": "glassWater",
    "💪": "dumbbell",
    "🏋️": "dumbbell",
    "🏋️‍♂️": "dumbbell",
    "🏋️‍♀️": "dumbbell",
    "🔥": "flame",
    "🌸": "flower2",
    "👣": "footprints",
    "🚶": "footprints",
    "🎓": "graduationCap",
    "🤝": "handHeart",
    "🫶": "handHeart",
    "🧠": "brain",
    "📚": "book",
    "📖": "book",
    "💼": "briefcase",
    "❤️": "heart",
    "💙": "heart",
    "🏠": "house",
    "💻": "laptop",
    "🌐": "languages",
    "🗣️": "languages",
    "🌱": "leaf",
    "🌿": "leaf",
    "✅": "listChecks",
    "📝": "notebookPen",
    "🏆": "medal",
    "🏅": "medal",
    "☀️": "sunrise",
    "🌅": "sunrise",
    "🌙": "moon",
    "😴": "moon",
    "🎵": "music",
    "🎶": "music",
    "✍️": "penLine",
    "🖊️": "penLine",
    "🍎": "apple",
    "💊": "pill",
    "✈️": "plane",
    "🥗": "utensils",
    "🍽️": "utensils",
    "📞": "phone",
    "🙂": "smile",
    "😊": "smile",
    "🎯": "target",
    "⏱️": "timer",
    "💰": "wallet",
    "👛": "wallet",
    "🍷🚫": "wineOff"
};

const ICON_BY_KEY = new Map<string, LucideIcon>(
    HABIT_ICON_OPTIONS.map((option) => [option.key, option.icon])
);

export const DEFAULT_HABIT_ICON_KEY = "sparkles";

export function normalizeHabitIconKey(value: string | undefined): string {
    const trimmed = value?.trim();
    if (!trimmed) return DEFAULT_HABIT_ICON_KEY;
    if (ICON_BY_KEY.has(trimmed)) return trimmed;
    return LEGACY_EMOJI_TO_ICON_KEY[trimmed] ?? DEFAULT_HABIT_ICON_KEY;
}

export function resolveHabitIcon(value: string | undefined): LucideIcon {
    return ICON_BY_KEY.get(normalizeHabitIconKey(value)) ?? Sparkles;
}
