import {
    type Icon as PhosphorIcon,
    Airplane,
    Alarm,
    AppleLogo,
    ArrowClockwise,
    ArrowRight,
    Barbell,
    Bed,
    Bicycle,
    BookOpen,
    BookOpenText,
    Brain,
    Briefcase,
    CalendarBlank,
    CalendarCheck,
    CaretRight,
    ChartBar,
    Check as CheckIcon,
    CheckSquare as CheckSquareIcon,
    Checks,
    ChefHat,
    CigaretteSlash,
    Clock,
    CloudCheck as CloudCheckIcon,
    CloudSlash,
    CloudWarning,
    Coffee,
    DownloadSimple,
    Drop,
    Flame,
    FlowerLotus,
    Footprints,
    ForkKnife,
    Funnel,
    Gear,
    GraduationCap,
    HandHeart,
    Heart,
    House,
    Kanban,
    Laptop,
    Leaf,
    MagnifyingGlass,
    Medal,
    Moon,
    MusicNotes,
    NotePencil,
    Notebook,
    PaintBrush,
    Pencil as PencilIcon,
    PencilLine as PencilLineIcon,
    Phone,
    Pill,
    PintGlass,
    Plus as PlusIcon,
    Prohibit,
    Pulse,
    Smiley,
    Sparkle,
    Square as SquareIcon,
    SquaresFour,
    StopCircle,
    SunHorizon,
    Target as TargetIcon,
    Timer,
    Trash,
    Translate,
    Wallet,
    Wine,
    X as XIcon
} from "@phosphor-icons/react";

export type LucideIcon = PhosphorIcon;

export {
    // Shared direct exports
    ArrowRight,
    BookOpen,
    BookOpenText,
    Brain,
    Briefcase,
    ChefHat,
    Coffee,
    Flame,
    Footprints,
    GraduationCap,
    HandHeart,
    Heart,
    House,
    Laptop,
    Leaf,
    Medal,
    Moon,
    Phone,
    Pill,
    Timer,
    // Lucide compatibility aliases
    Airplane as Plane,
    Alarm as AlarmClock,
    AppleLogo as Apple,
    ArrowClockwise as RefreshCcw,
    Barbell as Dumbbell,
    Bed as BedDouble,
    Bicycle as Bike,
    CalendarBlank as CalendarDays,
    CalendarCheck as CalendarCheck2,
    CaretRight as ChevronRight,
    ChartBar as BarChart3,
    CheckIcon as Check,
    CheckSquareIcon as CheckSquare,
    Checks as ListChecks,
    CigaretteSlash as CigaretteOff,
    Clock as Clock3,
    CloudCheckIcon as CloudCheck,
    CloudSlash as CloudOff,
    CloudWarning as CloudAlert,
    DownloadSimple as Download,
    Drop as Droplets,
    FlowerLotus as Flower2,
    ForkKnife as Utensils,
    Funnel as Filter,
    Gear as Settings,
    Kanban as FolderKanban,
    MagnifyingGlass as Search,
    MusicNotes as Music,
    NotePencil as SquarePen,
    Notebook as NotebookPen,
    PaintBrush as Brush,
    PencilIcon as Pencil,
    PencilLineIcon as PenLine,
    PencilLineIcon as PencilLine,
    PintGlass as GlassWater,
    PlusIcon as Plus,
    Prohibit as Ban,
    Pulse as Activity,
    Smiley as Smile,
    Sparkle as Sparkles,
    SquareIcon as Square,
    SquaresFour as LayoutGrid,
    StopCircle as CircleStop,
    SunHorizon as Sunrise,
    TargetIcon as Target,
    Trash as Trash2,
    Translate as Languages,
    Wallet,
    Wine as WineOff,
    XIcon as X,
    Leaf as CannabisOff
};
